#!/bin/bash

#########################
# a script by lazy-pwny #
#########################

## VARIABLES
datetoday=$(date | awk '{print $1,$3,$4" / "$2}')
s="https://www.ntv.com.tr/son-dakika"

#check internet

wget -q --spider http://google.com

if [ $? -eq 0 ]; then
    echo "Online" &> /dev/null  
else
    echo "[*] Offline"
    echo "cihazınız internete bağlı olmadığından güncel bilgi alınamıyor.."
    exit 1
fi
echo "yazılıyor"
{
    manset1=$(wget -q -O - $s | awk 'NR==354')
    manset2=$(wget -q -O - $s | awk 'NR==394')
    manset3=$(wget -q -O - $s | awk 'NR==434')
    manset4=$(wget -q -O - $s | awk 'NR==474')
    manset5=$(wget -q -O - $s | awk 'NR==514')
    echo "--$datetoday--"
    echo -e "\nSon Dakika[1]: $manset1\n"
    echo -e "Son Dakika[2]: $manset2\n"
    echo -e "Son Dakika[3]: $manset3\n"
    echo -e "Son Dakika[4]: $manset4\n"
    echo -e "Son Dakika[5]: $manset5\n"
    echo -e "\n a script by lazy-pwny https://github.com/lastpingu"
} > sondakika.txt   
echo "bitti"